language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: santoshpanna
  password:
    secure: JsnI1IkkKYN2Yhkz1GjPLggfBROIifavd0+HgoK8Jwu8ljOZfRgTDtHZuS7997QnAK8KdvBWvlD/miceKX6NNbUYBADKOFSz61Yj+ZSJL92ji/hIrkgMEaQhDoeR0V7dQe6zfk6ntz5BOrt+85j+g3e/EOe45NBCyBXGgLSHRlu+gu9RQ68nE2ZZ6IqhPlsXZWpVDsem6DHPAx8tMALWXMOx/gOP5fjp5KL/6FtR7vDZ6CZaRyrL/P6LNf5SbRnPlNRA30o1CZ2uRjUOHt9jfXQykDRLUXZX5KsHtfhXUSfKUBS4ZPVwwTEAJukSMOQRG854tzfeWEy++7/eiulAQXHOkvjegxKmEtvAAB1RIxyNn2nz7PIPCFIMFXRtkVKtaosOo+NfV3hWzWGtL4R+IT4Pw3nnD3r4FU5RlyzuG3p+YBgteBsLiHIjGtIrBtDYHG+BaCGf7ye39CZldA7VCcKJ7Z8Iyw3vK0gdKyb+GyZleedXArsHQjhzymecoYYLosWwjTH2EYKwGcloVZiwgwy4lJR3h7k9uYT1H3tNyWVrwRVBAxR08tACo0m1Z+Mgov3ieDGOt/lXngzNJS5ASCsU6i89Pbxw8r1QbCfnC1MpH6B8qxZ45XlF8Qsq0t8JWYoEitJ63ZogQiMFoQpbHcpynoQFhPr5uZdsPgjK7Zo=
  on:
    tags: true
    repo: santoshpanna/steamstorefront
    python: 3.8
